name: Codecov Example

# Run on every commit, schedule, and manual trigger
on:
  push:
    branches: [ main ]  # Run on main branch commits
  schedule:
    - cron: '0 2 * * 0'  # Run weekly on Sunday at 2 AM
  workflow_dispatch:  # Keep manual trigger option

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test with coverage
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat="opencover,cobertura"
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Optional: only needed for private repos
        file: '**/coverage.opencover.xml'
        fail_ci_if_error: false
        verbose: true
        
    # Generate HTML report for GitHub Pages
    - name: Generate HTML Report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:codecov-report" "-reporttypes:Html"
        
    - name: Extract coverage percentage
      id: coverage
      run: |
        # Extract line rate from the Cobertura XML
        LINE_RATE=$(grep -o 'line-rate="[0-9.]*"' */*/coverage.cobertura.xml | head -1 | grep -o '[0-9.]*')
        PERCENTAGE=$(echo "$LINE_RATE * 100" | bc)
        echo "Line coverage percentage: $PERCENTAGE%"
        echo "coverage_percentage=$PERCENTAGE" >> $GITHUB_OUTPUT
        
        # Create badge
        COLOR="red"
        if (( $(echo "$PERCENTAGE > 90" | bc -l) )); then
          COLOR="brightgreen"
        elif (( $(echo "$PERCENTAGE > 75" | bc -l) )); then
          COLOR="yellow"
        fi
        
        # Create badge with actual coverage percentage
        wget -O codecov-badge.svg "https://img.shields.io/badge/codecov-${PERCENTAGE}%25-${COLOR}"
        
    # Upload artifacts for debugging
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: codecov-coverage-report
        path: codecov-report

    # Deploy to GitHub Pages using the shared workflow
    - name: Deploy to GitHub Pages
      uses: ./.github/workflows/coveragetool-shared-deploy
      with:
        tool_name: codecov
        report_dir: codecov-report
        badge_path: codecov-badge.svg
        coverage_percentage: ${{ steps.coverage.outputs.coverage_percentage }}
