name: AltCover Example

# Run on every commit, schedule, and manual trigger
on:
  push:
    branches: [ main ]  # Run on main branch commits
  schedule:
    - cron: '0 5 * * 0'  # Run weekly on Sunday at 5 AM
  workflow_dispatch:  # Keep manual trigger option

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Install AltCover
      run: dotnet tool install --global altcover.global
        
    - name: Build
      run: dotnet build
      
    - name: Test with AltCover
      run: |
        # Record initial state
        dotnet altcover --collect
        # Run tests
        dotnet test --no-build
        # Get coverage report
        dotnet altcover --opencover -o coverage.opencover.xml
        
        # Convert to Cobertura for consistent HTML reporting
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:coverage.opencover.xml" "-targetdir:." "-reporttypes:Cobertura"
        
    - name: Generate Report
      run: |
        reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:altcover-report" "-reporttypes:Html"
        
    - name: Extract coverage percentage
      id: coverage
      run: |
        # Extract line rate from the Cobertura XML
        LINE_RATE=$(grep -o 'line-rate="[0-9.]*"' coverage.cobertura.xml | head -1 | grep -o '[0-9.]*')
        PERCENTAGE=$(echo "$LINE_RATE * 100" | bc)
        echo "Line coverage percentage: $PERCENTAGE%"
        echo "coverage_percentage=$PERCENTAGE" >> $GITHUB_OUTPUT
        
        # Create badge
        COLOR="red"
        if (( $(echo "$PERCENTAGE > 90" | bc -l) )); then
          COLOR="brightgreen"
        elif (( $(echo "$PERCENTAGE > 75" | bc -l) )); then
          COLOR="yellow"
        fi
        
        # Create badge with actual coverage percentage
        wget -O altcover-badge.svg "https://img.shields.io/badge/altcover-${PERCENTAGE}%25-${COLOR}"
        
    # Deploy to GitHub Pages using the shared workflow
    - name: Deploy to GitHub Pages
      uses: ./.github/workflows/coveragetool-shared-deploy
      with:
        tool_name: altcover
        report_dir: altcover-report
        badge_path: altcover-badge.svg
        coverage_percentage: ${{ steps.coverage.outputs.coverage_percentage }}
